# Generated by Django 6.0.1 on 2026-01-09 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='usersubject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'subject', 'year')},
        ),
    ]
