# Generated by Django 6.0.1 on 2026-01-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_subject_alter_score_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubject',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
