# Generated by Django 6.0.1 on 2026-01-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message_audio_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_pic',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
