# Generated by Django 6.0.1 on 2026-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_userprofile_last_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
